import bcrypt from 'bcryptjs';

const dataShop = {
  users: [
    {
      name: "Filippo",
      email: "filippo.moretti6@gmail",
      password: bcrypt.hashSync("1234", 8),
      isAdmin:true,
    },
    {
        name: "John",
        email: "filippo.cicco6@gmail",
        password: bcrypt.hashSync("1234", 8),
        isAdmin:true,
      },
  ],
  products: [
    {
      _id: "1",
      name: "product 1",
      category: "season 1",
      image: "product-1.jpeg",
      price: 80,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Suuuper coool!!!",
    },
    {
      _id: "2",
      name: "product 2",
      category: "season 1",
      image: "product-2.jpeg",
      price: 80,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Suuuper coool!!!",
    },
    {
      _id: "3",
      name: "product 3",
      category: "season 1",
      image: "product-3.jpeg",
      price: 80,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Suuuper coool!!!",
    },
    {
      _id: "4",
      name: "product 4",
      category: "season 1",
      image: "product-4.jpeg",
      price: 80,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Suuuper coool!!!",
    },
    {
      _id: "5",
      name: "product 5",
      category: "season 1",
      image: "product-5.jpeg",
      price: 80,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Suuuper coool!!!",
    },
    {
      _id: "6",
      name: "product 6",
      category: "season 1",
      image: "product-6.jpeg",
      price: 80,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Suuuper coool!!!",
    },
  ],
};
export default dataShop;
